# Generated by Django 5.1.4 on 2025-01-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lihamuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
