# Generated by Django 5.1.4 on 2025-01-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_lihamuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lihamuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
