# Generated by Django 5.1.4 on 2025-02-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_lihamuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lihamuser',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover_pics'),
        ),
    ]
