# Generated by Django 5.1.4 on 2025-01-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0002_remove_friendrequest_is_active_friendrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
    ]
